### ISSUE TITLE
Missing recipes on swords

### ISSUE THREAD

**Issue by georg94** [MustangXPress7/Cyan-Warrior-Swords-Minecraft-Mod-#1]
The recipe for the Wolf Sword is missing in the CyanWarriorSwordMod.java

**Comment by MustangXPress7** [comment]
Fixed!

**Comment by georg94** [comment]
Actually the recipes of the Triender Sword and the Cyan Sword missing too.
If I find some time I can make a pull request.

**Comment by MustangXPress7** [comment]
Sweet. I'll try to decompile my old releases to see what happened to it.

**Comment by MustangXPress7** [comment]
Wait, just find them, they weren't missing, they were shapeless recipes.
