### ISSUE TITLE
Can't craft Beast Essence.

### ISSUE THREAD

**Issue by gabriel25gomes** [MustangXPress7/Cyan-Warrior-Swords-Minecraft-Mod-#2]
A few days ago, I was playing Minecraft with the Cyan Warrior Swords Mod, and I saw the Cyan Sword, that needs all the essences of the Mod. I crafted all, but there is no recipe for Beast Essence, and I don't know how to get it. I don't know if it was meant to be this way, or is a bug. Please help me. I don't wanna enter Creative to get the Beast Essence....

**Comment by MustangXPress7** [comment]
Are you playing on the last version of this mod?

**Comment by gabriel25gomes** [comment]
Yes, version 2.0.1, on Minecraft 1.7.10.

**Comment by MustangXPress7** [comment]
Wow, so I may have to fix it soon. Hope I have a mod update before this weekend.

**Comment by MustangXPress7** [comment]
And thanks for reporting! ^_^

**Comment by gabriel25gomes** [comment]
Ok, man. Thank you so much! Only by chance, i'm from Brazil, and your Mod is so good that reached other Country... :D

**Comment by MustangXPress7** [comment]
Thanks! By the way I'm from Spain ;)

**Comment by gabriel25gomes** [comment]
That's cool! Globalization hahahaha.

**Comment by gabriel25gomes** [comment]
Thanks dude!

**Comment by Vincenzorf** [comment]
Hey dude, I am playing in 1.7.10 latest version, 2.1.2 of Cyan Warriors Mod, and I noticed that there is a new sword, The Thunder Zeus sword i think. But this sword does not have a normal look, but a black and pink block look, as if it were bug. Can you explain what is that?
